# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa6786653abd5f8fcfa5fff1863b43772e8f0ebeb7233de68804c84fc0d985d4e7de909cb79607371e1ec75d58c2f59052e1026895e583973f071e7e6f23ade8

test:
  secret_key_base: ab98fc43dbd5870bc4f11076d4f5e91a9bd39e1f6bfc90f0f6b9fb4688c9dc5d678c23b5873eb55258db5d3776e67dec1c927feae3a7f4c7ededfa1606413b19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
