# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62dc4c5ee668cb1616e390477256f62f7ef7a7b6caf35552245d174f4858486169209aa440c4246535ba677ce25ad77eaf23e5ae08c06cf705a19da909acd0f2

test:
  secret_key_base: b65a0f79526f01fcb85319fec3c384f0b76932433c94435ee13adcd0cb027130d809ef11fe00f7caffdd7b1eb569b51b58dd40490eb34298fa7bd9acf03eb4a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
