# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

StockIndex.all.map(&:destroy)
Company.all.map(&:destroy)

StockIndex.create!(
  name: "S&P 500 Component Stocks",
  description: "The S&P 500 stock market index, maintained by S&P Dow Jones Indices, comprises 505 common stocks issued by 500 large-cap companies and traded on American stock exchanges, and covers about 75 percent of the American equity market by capitalization. The index is weighted by free-float market capitalization, so more valuable companies account for relatively more of the index. The index constituents and the constituent weights are updated regularly using rules published by S&P Dow Jones Indices. Although the index is called the S&P \"500\", the index contains 505 stocks because it includes two share classes of stock from 5 of its component companies.[1][2] The index constituents listed below were current as of September 25, 2015.",
  symbols: %w(MMM ABT ABBV ACN ACE ATVI ADBE ADT AAP AES AET AFL AMG A GAS APD ARG AKAM AA AGN ALXN ALLE ADS ALL ALTR MO AMZN AEE AAL AEP AXP AIG AMT AMP ABC AME AMGN APH APC ADI AON APA AIV AAPL AMAT ADM AIZ T ADSK ADP AN AZO AVGO AVB AVY BHI BLL BAC BK BCR BXLT BAX BBT BDX BBBY BRK-B BBY BIIB BLK HRB BA BWA BXP BSX BMY BRCM BF-B CHRW CA CVC COG CAM CPB COF CAH HSIC KMX CCL CAT CBG CBS CELG CNP CTL CERN CF SCHW CHK CVX CMG CB CI XEC CINF CTAS CSCO C CTXS CLX CME CMS COH KO CCE CTSH CL CPGX CMCSA CMCSK CMA CSC CAG COP CNX ED STZ GLW COST CCI CSX CMI CVS DHI DHR DRI DVA DE DLPH DAL XRAY DVN DO DFS DISCA DISCK DG DLTR D DOV DOW DPS DTE DD DUK DNB ETFC EMN ETN EBAY ECL EIX EW EA EMC EMR ENDP ESV ETR EOG EQT EFX EQIX EQR ESS EL ES EXC EXPE EXPD ESRX XOM FFIV FB FAST FDX FIS FITB FSLR FE FISV FLIR FLS FLR FMC FTI F FOSL BEN FCX FTR GME GPS GRMN GD GE GGP GIS GM GPC GNW GILD GS GT GOOGL GOOG GWW HAL HBI HOG HAR HRS HIG HAS HCA HCP HCN HP HES HPQ HD HON HRL HST HCBK HUM HBAN ITW IR INTC ICE IBM IP IPG IFF INTU ISRG IVZ IRM JEC JBHT JNJ JCI JOY JPM JNPR KSU K KEY GMCR KMB KIM KMI KLAC KSS KHC KR LB LLL LH LRCX LM LEG LEN LVLT LUK LLY LNC LLTC LMT L LOW LYB MTB MAC M MNK MRO MPC MAR MMC MLM MAS MA MAT MKC MCD MHFI MCK MJN WRK MDT MRK MET KORS MCHP MU MSFT MHK TAP MDLZ MON MNST MCO MS MOS MSI MUR MYL NDAQ NOV NAVI NTAP NFLX NWL NFX NEM NWSA NWS NEE NLSN NKE NI NBL JWN NSC NTRS NOC NRG NUE NVDA ORLY OXY OMC OKE ORCL OI PCAR PH PDCO PAYX PYPL PNR PBCT POM PEP PKI PRGO PFE PCG PM PSX PNW PXD PBI PCL PNC RL PPG PPL PX PCP PCLN PFG PG PGR PLD PRU PEG PSA PHM PVH QRVO PWR QCOM DGX RRC RTN O RHT REGN RF RSG RAI RHI ROK COL ROP ROST RCL R CRM SNDK SCG SLB SNI STX SEE SRE SHW SIAL SIG SPG SWKS SLG SJM SNA SO LUV SWN SE STJ SWK SPLS SBUX HOT STT SRCL SYK STI SYMC SYY TROW TGT TEL TE TGNA THC TDC TSO TXN TXT HSY TRV TMO TIF TWX TWC TJX TMK TSS TSCO RIG TRIP FOXA FOX TSN TYC USB UA UNP UAL UNH UPS URI UTX UHS UNM URBN VFC VLO VAR VTR VRSN VZ VRTX VIAB V VNO VMC WMT WBA DIS WM WAT ANTM WFC WDC WU WY WHR WFM WMB WEC WYN WYNN XEL XRX XLNX XL XYL YHOO YUM ZBH ZION ZTS),
)

stocks = Hashie::Mash.new(
  MMM: {name:"3M Company",sector:"Industrials",sub_industry:"Industrials"},
  ABT: {name:"Abbott Laboratories",sector:"Health Care",sub_industry:"Health Care"},
  ABBV: {name:"AbbVie",sector:"Health Care",sub_industry:"Health Care"},
  ACN: {name:"Accenture plc",sector:"Information Technology",sub_industry:"Information Technology"},
  ACE: {name:"ACE Limited",sector:"Financials",sub_industry:"Financials"},
  ATVI: {name:"Activision Blizzard",sector:"Information Technology",sub_industry:"Information Technology"},
  ADBE: {name:"Adobe Systems Inc",sector:"Information Technology",sub_industry:"Information Technology"},
  ADT: {name:"ADT Corp",sector:"Industrials",sub_industry:"Industrials"},
  AAP: {name:"Advance Auto Parts",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  AES: {name:"AES Corp",sector:"Utilities",sub_industry:"Utilities"},
  AET: {name:"Aetna Inc",sector:"Health Care",sub_industry:"Health Care"},
  AFL: {name:"AFLAC Inc",sector:"Financials",sub_industry:"Financials"},
  AMG: {name:"Affiliated Managers Group Inc",sector:"Financials",sub_industry:"Financials"},
  A: {name:"Agilent Technologies Inc",sector:"Health Care",sub_industry:"Health Care"},
  GAS: {name:"AGL Resources Inc.",sector:"Utilities",sub_industry:"Utilities"},
  APD: {name:"Air Products & Chemicals Inc",sector:"Materials",sub_industry:"Materials"},
  ARG: {name:"Airgas Inc",sector:"Materials",sub_industry:"Materials"},
  AKAM: {name:"Akamai Technologies Inc",sector:"Information Technology",sub_industry:"Information Technology"},
  AA: {name:"Alcoa Inc",sector:"Materials",sub_industry:"Materials"},
  AGN: {name:"Allergan plc",sector:"Health Care",sub_industry:"Health Care"},
  ALXN: {name:"Alexion Pharmaceuticals",sector:"Health Care",sub_industry:"Health Care"},
  ALLE: {name:"Allegion",sector:"Industrials",sub_industry:"Industrials"},
  ADS: {name:"Alliance Data Systems",sector:"Information Technology",sub_industry:"Information Technology"},
  ALL: {name:"Allstate Corp",sector:"Financials",sub_industry:"Financials"},
  ALTR: {name:"Altera Corp",sector:"Information Technology",sub_industry:"Information Technology"},
  MO: {name:"Altria Group Inc",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  AMZN: {name:"Amazon.com Inc",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  AEE: {name:"Ameren Corp",sector:"Utilities",sub_industry:"Utilities"},
  AAL: {name:"American Airlines Group",sector:"Industrials",sub_industry:"Industrials"},
  AEP: {name:"American Electric Power",sector:"Utilities",sub_industry:"Utilities"},
  AXP: {name:"American Express Co",sector:"Financials",sub_industry:"Financials"},
  AIG: {name:"American International Group, Inc.",sector:"Financials",sub_industry:"Financials"},
  AMT: {name:"American Tower Corp A",sector:"Financials",sub_industry:"Financials"},
  AMP: {name:"Ameriprise Financial",sector:"Financials",sub_industry:"Financials"},
  ABC: {name:"AmerisourceBergen Corp",sector:"Health Care",sub_industry:"Health Care"},
  AME: {name:"Ametek",sector:"Industrials",sub_industry:"Industrials"},
  AMGN: {name:"Amgen Inc",sector:"Health Care",sub_industry:"Health Care"},
  APH: {name:"Amphenol Corp A",sector:"Industrials",sub_industry:"Industrials"},
  APC: {name:"Anadarko Petroleum Corp",sector:"Energy",sub_industry:"Energy"},
  ADI: {name:"Analog Devices, Inc.",sector:"Information Technology",sub_industry:"Information Technology"},
  AON: {name:"Aon plc",sector:"Financials",sub_industry:"Financials"},
  APA: {name:"Apache Corporation",sector:"Energy",sub_industry:"Energy"},
  AIV: {name:"Apartment Investment & Mgmt",sector:"Financials",sub_industry:"Financials"},
  AAPL: {name:"Apple Inc.",sector:"Information Technology",sub_industry:"Information Technology"},
  AMAT: {name:"Applied Materials Inc",sector:"Information Technology",sub_industry:"Information Technology"},
  ADM: {name:"Archer-Daniels-Midland Co",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  AIZ: {name:"Assurant Inc",sector:"Financials",sub_industry:"Financials"},
  T: {name:"AT&T Inc",sector:"Telecommunications Services",sub_industry:"Telecommunications Services"},
  ADSK: {name:"Autodesk Inc",sector:"Information Technology",sub_industry:"Information Technology"},
  ADP: {name:"Automatic Data Processing",sector:"Information Technology",sub_industry:"Information Technology"},
  AN: {name:"AutoNation Inc",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  AZO: {name:"AutoZone Inc",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  AVGO: {name:"Avago Technologies",sector:"Information Technology",sub_industry:"Information Technology"},
  AVB: {name:"AvalonBay Communities, Inc.",sector:"Financials",sub_industry:"Financials"},
  AVY: {name:"Avery Dennison Corp",sector:"Materials",sub_industry:"Materials"},
  BHI: {name:"Baker Hughes Inc",sector:"Energy",sub_industry:"Energy"},
  BLL: {name:"Ball Corp",sector:"Materials",sub_industry:"Materials"},
  BAC: {name:"Bank of America Corp",sector:"Financials",sub_industry:"Financials"},
  BK: {name:"The Bank of New York Mellon Corp.",sector:"Financials",sub_industry:"Financials"},
  BCR: {name:"Bard (C.R.) Inc.",sector:"Health Care",sub_industry:"Health Care"},
  BXLT: {name:"Baxalta",sector:"Health Care",sub_industry:"Health Care"},
  BAX: {name:"Baxter International Inc.",sector:"Health Care",sub_industry:"Health Care"},
  BBT: {name:"BB&T Corporation",sector:"Financials",sub_industry:"Financials"},
  BDX: {name:"Becton Dickinson",sector:"Health Care",sub_industry:"Health Care"},
  BBBY: {name:"Bed Bath & Beyond",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  BRK: {name:"Berkshire Hathaway",sector:"Financials",sub_industry:"Financials"},
  BBY: {name:"Best Buy Co. Inc.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  BIIB: {name:"BIOGEN IDEC Inc.",sector:"Health Care",sub_industry:"Health Care"},
  BLK: {name:"BlackRock",sector:"Financials",sub_industry:"Financials"},
  HRB: {name:"Block H&R",sector:"Financials",sub_industry:"Financials"},
  BA: {name:"Boeing Company",sector:"Industrials",sub_industry:"Industrials"},
  BWA: {name:"BorgWarner",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  BXP: {name:"Boston Properties",sector:"Financials",sub_industry:"Financials"},
  BSX: {name:"Boston Scientific",sector:"Health Care",sub_industry:"Health Care"},
  BMY: {name:"Bristol-Myers Squibb",sector:"Health Care",sub_industry:"Health Care"},
  BRCM: {name:"Broadcom Corporation",sector:"Information Technology",sub_industry:"Information Technology"},
  BF: {name:"Brown-Forman Corporation",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  CHRW: {name:"C. H. Robinson Worldwide",sector:"Industrials",sub_industry:"Industrials"},
  CA: {name:"CA, Inc.",sector:"Information Technology",sub_industry:"Information Technology"},
  CVC: {name:"Cablevision Systems Corp.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  COG: {name:"Cabot Oil & Gas",sector:"Energy",sub_industry:"Energy"},
  CAM: {name:"Cameron International Corp.",sector:"Energy",sub_industry:"Energy"},
  CPB: {name:"Campbell Soup",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  COF: {name:"Capital One Financial",sector:"Financials",sub_industry:"Financials"},
  CAH: {name:"Cardinal Health Inc.",sector:"Health Care",sub_industry:"Health Care"},
  HSIC: {name:"Henry Schein",sector:"Health Care",sub_industry:"Health Care"},
  KMX: {name:"Carmax Inc",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  CCL: {name:"Carnival Corp.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  CAT: {name:"Caterpillar Inc.",sector:"Industrials",sub_industry:"Industrials"},
  CBG: {name:"CBRE Group",sector:"Financials",sub_industry:"Financials"},
  CBS: {name:"CBS Corp.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  CELG: {name:"Celgene Corp.",sector:"Health Care",sub_industry:"Health Care"},
  CNP: {name:"CenterPoint Energy",sector:"Utilities",sub_industry:"Utilities"},
  CTL: {name:"CenturyLink Inc",sector:"Telecommunications Services",sub_industry:"Telecommunications Services"},
  CERN: {name:"Cerner",sector:"Health Care",sub_industry:"Health Care"},
  CF: {name:"CF Industries Holdings Inc",sector:"Materials",sub_industry:"Materials"},
  SCHW: {name:"Charles Schwab Corporation",sector:"Financials",sub_industry:"Financials"},
  CHK: {name:"Chesapeake Energy",sector:"Energy",sub_industry:"Energy"},
  CVX: {name:"Chevron Corp.",sector:"Energy",sub_industry:"Energy"},
  CMG: {name:"Chipotle Mexican Grill",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  CB: {name:"Chubb Corp.",sector:"Financials",sub_industry:"Financials"},
  CI: {name:"CIGNA Corp.",sector:"Health Care",sub_industry:"Health Care"},
  XEC: {name:"Cimarex Energy",sector:"Energy",sub_industry:"Energy"},
  CINF: {name:"Cincinnati Financial",sector:"Financials",sub_industry:"Financials"},
  CTAS: {name:"Cintas Corporation",sector:"Industrials",sub_industry:"Industrials"},
  CSCO: {name:"Cisco Systems",sector:"Information Technology",sub_industry:"Information Technology"},
  C: {name:"Citigroup Inc.",sector:"Financials",sub_industry:"Financials"},
  CTXS: {name:"Citrix Systems",sector:"Information Technology",sub_industry:"Information Technology"},
  CLX: {name:"The Clorox Company",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  CME: {name:"CME Group Inc.",sector:"Financials",sub_industry:"Financials"},
  CMS: {name:"CMS Energy",sector:"Utilities",sub_industry:"Utilities"},
  COH: {name:"Coach Inc.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  KO: {name:"The Coca Cola Company",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  CCE: {name:"Coca-Cola Enterprises",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  CTSH: {name:"Cognizant Technology Solutions",sector:"Information Technology",sub_industry:"Information Technology"},
  CL: {name:"Colgate-Palmolive",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  CPGX: {name:"Columbia Pipeline Group Inc",sector:"Energy",sub_industry:"Energy"},
  CMCSA: {name:"Comcast A Corp",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  CMCSK: {name:"Comcast Special Corp Class A",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  CMA: {name:"Comerica Inc.",sector:"Financials",sub_industry:"Financials"},
  CSC: {name:"Computer Sciences Corp.",sector:"Information Technology",sub_industry:"Information Technology"},
  CAG: {name:"ConAgra Foods Inc.",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  COP: {name:"ConocoPhillips",sector:"Energy",sub_industry:"Energy"},
  CNX: {name:"CONSOL Energy Inc.",sector:"Energy",sub_industry:"Energy"},
  ED: {name:"Consolidated Edison",sector:"Utilities",sub_industry:"Utilities"},
  STZ: {name:"Constellation Brands",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  GLW: {name:"Corning Inc.",sector:"Industrials",sub_industry:"Industrials"},
  COST: {name:"Costco Co.",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  CCI: {name:"Crown Castle International Corp.",sector:"Financials",sub_industry:"Financials"},
  CSX: {name:"CSX Corp.",sector:"Industrials",sub_industry:"Industrials"},
  CMI: {name:"Cummins Inc.",sector:"Industrials",sub_industry:"Industrials"},
  CVS: {name:"CVS Caremark Corp.",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  DHI: {name:"D. R. Horton",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  DHR: {name:"Danaher Corp.",sector:"Industrials",sub_industry:"Industrials"},
  DRI: {name:"Darden Restaurants",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  DVA: {name:"DaVita Inc.",sector:"Health Care",sub_industry:"Health Care"},
  DE: {name:"Deere & Co.",sector:"Industrials",sub_industry:"Industrials"},
  DLPH: {name:"Delphi Automotive",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  DAL: {name:"Delta Air Lines",sector:"Industrials",sub_industry:"Industrials"},
  XRAY: {name:"Dentsply International",sector:"Health Care",sub_industry:"Health Care"},
  DVN: {name:"Devon Energy Corp.",sector:"Energy",sub_industry:"Energy"},
  DO: {name:"Diamond Offshore Drilling",sector:"Energy",sub_industry:"Energy"},
  DFS: {name:"Discover Financial Services",sector:"Financials",sub_industry:"Financials"},
  DISCA: {name:"Discovery Communications-A",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  DISCK: {name:"Discovery Communications-C",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  DG: {name:"Dollar General",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  DLTR: {name:"Dollar Tree",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  D: {name:"Dominion Resources",sector:"Utilities",sub_industry:"Utilities"},
  DOV: {name:"Dover Corp.",sector:"Industrials",sub_industry:"Industrials"},
  DOW: {name:"Dow Chemical",sector:"Materials",sub_industry:"Materials"},
  DPS: {name:"Dr Pepper Snapple Group",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  DTE: {name:"DTE Energy Co.",sector:"Utilities",sub_industry:"Utilities"},
  DD: {name:"Du Pont (E.I.)",sector:"Materials",sub_industry:"Materials"},
  DUK: {name:"Duke Energy",sector:"Utilities",sub_industry:"Utilities"},
  DNB: {name:"Dun & Bradstreet",sector:"Industrials",sub_industry:"Industrials"},
  ETFC: {name:"E*Trade",sector:"Financials",sub_industry:"Financials"},
  EMN: {name:"Eastman Chemical",sector:"Materials",sub_industry:"Materials"},
  ETN: {name:"Eaton Corporation",sector:"Industrials",sub_industry:"Industrials"},
  EBAY: {name:"eBay Inc.",sector:"Information Technology",sub_industry:"Information Technology"},
  ECL: {name:"Ecolab Inc.",sector:"Materials",sub_industry:"Materials"},
  EIX: {name:"Edison Int'l",sector:"Utilities",sub_industry:"Utilities"},
  EW: {name:"Edwards Lifesciences",sector:"Health Care",sub_industry:"Health Care"},
  EA: {name:"Electronic Arts",sector:"Information Technology",sub_industry:"Information Technology"},
  EMC: {name:"EMC Corp.",sector:"Information Technology",sub_industry:"Information Technology"},
  EMR: {name:"Emerson Electric Company",sector:"Industrials",sub_industry:"Industrials"},
  ENDP: {name:"Endo International",sector:"Health Care",sub_industry:"Health Care"},
  ESV: {name:"Ensco plc",sector:"Energy",sub_industry:"Energy"},
  ETR: {name:"Entergy Corp.",sector:"Utilities",sub_industry:"Utilities"},
  EOG: {name:"EOG Resources",sector:"Energy",sub_industry:"Energy"},
  EQT: {name:"EQT Corporation",sector:"Energy",sub_industry:"Energy"},
  EFX: {name:"Equifax Inc.",sector:"Financials",sub_industry:"Financials"},
  EQIX: {name:"Equinix",sector:"Information Technology",sub_industry:"Information Technology"},
  EQR: {name:"Equity Residential",sector:"Financials",sub_industry:"Financials"},
  ESS: {name:"Essex Property Trust Inc",sector:"Financials",sub_industry:"Financials"},
  EL: {name:"Estee Lauder Cos.",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  ES: {name:"Eversource Energy",sector:"Utilities",sub_industry:"Utilities"},
  EXC: {name:"Exelon Corp.",sector:"Utilities",sub_industry:"Utilities"},
  EXPE: {name:"Expedia Inc.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  EXPD: {name:"Expeditors Int'l",sector:"Industrials",sub_industry:"Industrials"},
  ESRX: {name:"Express Scripts",sector:"Health Care",sub_industry:"Health Care"},
  XOM: {name:"Exxon Mobil Corp.",sector:"Energy",sub_industry:"Energy"},
  FFIV: {name:"F5 Networks",sector:"Information Technology",sub_industry:"Information Technology"},
  FB: {name:"Facebook",sector:"Information Technology",sub_industry:"Information Technology"},
  FAST: {name:"Fastenal Co",sector:"Industrials",sub_industry:"Industrials"},
  FDX: {name:"FedEx Corporation",sector:"Industrials",sub_industry:"Industrials"},
  FIS: {name:"Fidelity National Information Services",sector:"Information Technology",sub_industry:"Information Technology"},
  FITB: {name:"Fifth Third Bancorp",sector:"Financials",sub_industry:"Financials"},
  FSLR: {name:"First Solar Inc",sector:"Information Technology",sub_industry:"Information Technology"},
  FE: {name:"FirstEnergy Corp",sector:"Utilities",sub_industry:"Utilities"},
  FISV: {name:"Fiserv Inc",sector:"Information Technology",sub_industry:"Information Technology"},
  FLIR: {name:"FLIR Systems",sector:"Industrials",sub_industry:"Industrials"},
  FLS: {name:"Flowserve Corporation",sector:"Industrials",sub_industry:"Industrials"},
  FLR: {name:"Fluor Corp.",sector:"Industrials",sub_industry:"Industrials"},
  FMC: {name:"FMC Corporation",sector:"Materials",sub_industry:"Materials"},
  FTI: {name:"FMC Technologies Inc.",sector:"Energy",sub_industry:"Energy"},
  F: {name:"Ford Motor",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  FOSL: {name:"Fossil, Inc.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  BEN: {name:"Franklin Resources",sector:"Financials",sub_industry:"Financials"},
  FCX: {name:"Freeport-McMoran Cp & Gld",sector:"Materials",sub_industry:"Materials"},
  FTR: {name:"Frontier Communications",sector:"Telecommunications Services",sub_industry:"Telecommunications Services"},
  GME: {name:"GameStop Corp.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  GPS: {name:"Gap (The)",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  GRMN: {name:"Garmin Ltd.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  GD: {name:"General Dynamics",sector:"Industrials",sub_industry:"Industrials"},
  GE: {name:"General Electric",sector:"Industrials",sub_industry:"Industrials"},
  GGP: {name:"General Growth Properties Inc.",sector:"Financials",sub_industry:"Financials"},
  GIS: {name:"General Mills",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  GM: {name:"General Motors",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  GPC: {name:"Genuine Parts",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  GNW: {name:"Genworth Financial Inc.",sector:"Financials",sub_industry:"Financials"},
  GILD: {name:"Gilead Sciences",sector:"Health Care",sub_industry:"Health Care"},
  GS: {name:"Goldman Sachs Group",sector:"Financials",sub_industry:"Financials"},
  GT: {name:"Goodyear Tire & Rubber",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  GOOGL: {name:"Google Inc Class A",sector:"Information Technology",sub_industry:"Information Technology"},
  GOOG: {name:"Google Inc Class C",sector:"Information Technology",sub_industry:"Information Technology"},
  GWW: {name:"Grainger (W.W.) Inc.",sector:"Industrials",sub_industry:"Industrials"},
  HAL: {name:"Halliburton Co.",sector:"Energy",sub_industry:"Energy"},
  HBI: {name:"Hanesbrands Inc",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  HOG: {name:"Harley-Davidson",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  HAR: {name:"Harman Int'l Industries",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  HRS: {name:"Harris Corporation",sector:"Information Technology",sub_industry:"Information Technology"},
  HIG: {name:"Hartford Financial Svc.Gp.",sector:"Financials",sub_industry:"Financials"},
  HAS: {name:"Hasbro Inc.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  HCA: {name:"HCA Holdings",sector:"Health Care",sub_industry:"Health Care"},
  HCP: {name:"HCP Inc.",sector:"Financials",sub_industry:"Financials"},
  HCN: {name:"Health Care REIT, Inc.",sector:"Financials",sub_industry:"Financials"},
  HP: {name:"Helmerich & Payne",sector:"Energy",sub_industry:"Energy"},
  HES: {name:"Hess Corporation",sector:"Energy",sub_industry:"Energy"},
  HPQ: {name:"Hewlett-Packard",sector:"Information Technology",sub_industry:"Information Technology"},
  HD: {name:"Home Depot",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  HON: {name:"Honeywell Int'l Inc.",sector:"Industrials",sub_industry:"Industrials"},
  HRL: {name:"Hormel Foods Corp.",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  HST: {name:"Host Hotels & Resorts",sector:"Financials",sub_industry:"Financials"},
  HCBK: {name:"Hudson City Bancorp",sector:"Financials",sub_industry:"Financials"},
  HUM: {name:"Humana Inc.",sector:"Health Care",sub_industry:"Health Care"},
  HBAN: {name:"Huntington Bancshares",sector:"Financials",sub_industry:"Financials"},
  ITW: {name:"Illinois Tool Works",sector:"Industrials",sub_industry:"Industrials"},
  IR: {name:"Ingersoll-Rand PLC",sector:"Industrials",sub_industry:"Industrials"},
  INTC: {name:"Intel Corp.",sector:"Information Technology",sub_industry:"Information Technology"},
  ICE: {name:"Intercontinental Exchange",sector:"Financials",sub_industry:"Financials"},
  IBM: {name:"International Bus. Machines",sector:"Information Technology",sub_industry:"Information Technology"},
  IP: {name:"International Paper",sector:"Materials",sub_industry:"Materials"},
  IPG: {name:"Interpublic Group",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  IFF: {name:"Intl Flavors & Fragrances",sector:"Materials",sub_industry:"Materials"},
  INTU: {name:"Intuit Inc.",sector:"Information Technology",sub_industry:"Information Technology"},
  ISRG: {name:"Intuitive Surgical Inc.",sector:"Health Care",sub_industry:"Health Care"},
  IVZ: {name:"Invesco Ltd.",sector:"Financials",sub_industry:"Financials"},
  IRM: {name:"Iron Mountain Incorporated",sector:"Industrials",sub_industry:"Industrials"},
  JEC: {name:"Jacobs Engineering Group",sector:"Industrials",sub_industry:"Industrials"},
  JBHT: {name:"J. B. Hunt Transport Services",sector:"Industrials",sub_industry:"Industrials"},
  JNJ: {name:"Johnson & Johnson",sector:"Health Care",sub_industry:"Health Care"},
  JCI: {name:"Johnson Controls",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  JOY: {name:"Joy Global Inc.",sector:"Industrials",sub_industry:"Industrials"},
  JPM: {name:"JPMorgan Chase & Co.",sector:"Financials",sub_industry:"Financials"},
  JNPR: {name:"Juniper Networks",sector:"Information Technology",sub_industry:"Information Technology"},
  KSU: {name:"Kansas City Southern",sector:"Industrials",sub_industry:"Industrials"},
  K: {name:"Kellogg Co.",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  KEY: {name:"KeyCorp",sector:"Financials",sub_industry:"Financials"},
  GMCR: {name:"Keurig Green Mountain",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  KMB: {name:"Kimberly-Clark",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  KIM: {name:"Kimco Realty",sector:"Financials",sub_industry:"Financials"},
  KMI: {name:"Kinder Morgan",sector:"Energy",sub_industry:"Energy"},
  KLAC: {name:"KLA-Tencor Corp.",sector:"Information Technology",sub_industry:"Information Technology"},
  KSS: {name:"Kohl's Corp.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  KHC: {name:"Kraft Heinz Co",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  KR: {name:"Kroger Co.",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  LB: {name:"L Brands Inc.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  LLL: {name:"L-3 Communications Holdings",sector:"Industrials",sub_industry:"Industrials"},
  LH: {name:"Laboratory Corp. of America Holding",sector:"Health Care",sub_industry:"Health Care"},
  LRCX: {name:"Lam Research",sector:"Information Technology",sub_industry:"Information Technology"},
  LM: {name:"Legg Mason",sector:"Financials",sub_industry:"Financials"},
  LEG: {name:"Leggett & Platt",sector:"Industrials",sub_industry:"Industrials"},
  LEN: {name:"Lennar Corp.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  LVLT: {name:"Level 3 Communications",sector:"Telecommunications Services",sub_industry:"Telecommunications Services"},
  LUK: {name:"Leucadia National Corp.",sector:"Financials",sub_industry:"Financials"},
  LLY: {name:"Lilly (Eli) & Co.",sector:"Health Care",sub_industry:"Health Care"},
  LNC: {name:"Lincoln National",sector:"Financials",sub_industry:"Financials"},
  LLTC: {name:"Linear Technology Corp.",sector:"Information Technology",sub_industry:"Information Technology"},
  LMT: {name:"Lockheed Martin Corp.",sector:"Industrials",sub_industry:"Industrials"},
  L: {name:"Loews Corp.",sector:"Financials",sub_industry:"Financials"},
  LOW: {name:"Lowe's Cos.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  LYB: {name:"LyondellBasell",sector:"Materials",sub_industry:"Materials"},
  MTB: {name:"M&T Bank Corp.",sector:"Financials",sub_industry:"Financials"},
  MAC: {name:"Macerich",sector:"Financials",sub_industry:"Financials"},
  M: {name:"Macy's Inc.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  MNK: {name:"Mallinckrodt Plc",sector:"Health Care",sub_industry:"Health Care"},
  MRO: {name:"Marathon Oil Corp.",sector:"Energy",sub_industry:"Energy"},
  MPC: {name:"Marathon Petroleum",sector:"Energy",sub_industry:"Energy"},
  MAR: {name:"Marriott Int'l.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  MMC: {name:"Marsh & McLennan",sector:"Financials",sub_industry:"Financials"},
  MLM: {name:"Martin Marietta Materials",sector:"Materials",sub_industry:"Materials"},
  MAS: {name:"Masco Corp.",sector:"Industrials",sub_industry:"Industrials"},
  MA: {name:"Mastercard Inc.",sector:"Information Technology",sub_industry:"Information Technology"},
  MAT: {name:"Mattel Inc.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  MKC: {name:"McCormick & Co.",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  MCD: {name:"McDonald's Corp.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  MHFI: {name:"McGraw Hill Financial",sector:"Financials",sub_industry:"Financials"},
  MCK: {name:"McKesson Corp.",sector:"Health Care",sub_industry:"Health Care"},
  MJN: {name:"Mead Johnson",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  WRK: {name:"Westrock Co",sector:"Materials",sub_industry:"Materials"},
  MDT: {name:"Medtronic plc",sector:"Health Care",sub_industry:"Health Care"},
  MRK: {name:"Merck & Co.",sector:"Health Care",sub_industry:"Health Care"},
  MET: {name:"MetLife Inc.",sector:"Financials",sub_industry:"Financials"},
  KORS: {name:"Michael Kors Holdings",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  MCHP: {name:"Microchip Technology",sector:"Information Technology",sub_industry:"Information Technology"},
  MU: {name:"Micron Technology",sector:"Information Technology",sub_industry:"Information Technology"},
  MSFT: {name:"Microsoft Corp.",sector:"Information Technology",sub_industry:"Information Technology"},
  MHK: {name:"Mohawk Industries",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  TAP: {name:"Molson Coors Brewing Company",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  MDLZ: {name:"Mondelez International",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  MON: {name:"Monsanto Co.",sector:"Materials",sub_industry:"Materials"},
  MNST: {name:"Monster Beverage",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  MCO: {name:"Moody's Corp",sector:"Financials",sub_industry:"Financials"},
  MS: {name:"Morgan Stanley",sector:"Financials",sub_industry:"Financials"},
  MOS: {name:"The Mosaic Company",sector:"Materials",sub_industry:"Materials"},
  MSI: {name:"Motorola Solutions Inc.",sector:"Information Technology",sub_industry:"Information Technology"},
  MUR: {name:"Murphy Oil",sector:"Energy",sub_industry:"Energy"},
  MYL: {name:"Mylan N.V.",sector:"Health Care",sub_industry:"Health Care"},
  NDAQ: {name:"NASDAQ OMX Group",sector:"Financials",sub_industry:"Financials"},
  NOV: {name:"National Oilwell Varco Inc.",sector:"Energy",sub_industry:"Energy"},
  NAVI: {name:"Navient",sector:"Financials",sub_industry:"Financials"},
  NTAP: {name:"NetApp",sector:"Information Technology",sub_industry:"Information Technology"},
  NFLX: {name:"Netflix Inc.",sector:"Information Technology",sub_industry:"Information Technology"},
  NWL: {name:"Newell Rubbermaid Co.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  NFX: {name:"Newfield Exploration Co",sector:"Energy",sub_industry:"Energy"},
  NEM: {name:"Newmont Mining Corp. (Hldg. Co.)",sector:"Materials",sub_industry:"Materials"},
  NWSA: {name:"News Corp. Class A",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  NWS: {name:"News Corp. Class B",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  NEE: {name:"NextEra Energy",sector:"Utilities",sub_industry:"Utilities"},
  NLSN: {name:"Nielsen Holdings",sector:"Industrials",sub_industry:"Industrials"},
  NKE: {name:"Nike",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  NI: {name:"NiSource Inc.",sector:"Utilities",sub_industry:"Utilities"},
  NBL: {name:"Noble Energy Inc",sector:"Energy",sub_industry:"Energy"},
  JWN: {name:"Nordstrom",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  NSC: {name:"Norfolk Southern Corp.",sector:"Industrials",sub_industry:"Industrials"},
  NTRS: {name:"Northern Trust Corp.",sector:"Financials",sub_industry:"Financials"},
  NOC: {name:"Northrop Grumman Corp.",sector:"Industrials",sub_industry:"Industrials"},
  NRG: {name:"NRG Energy",sector:"Utilities",sub_industry:"Utilities"},
  NUE: {name:"Nucor Corp.",sector:"Materials",sub_industry:"Materials"},
  NVDA: {name:"Nvidia Corporation",sector:"Information Technology",sub_industry:"Information Technology"},
  ORLY: {name:"O'Reilly Automotive",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  OXY: {name:"Occidental Petroleum",sector:"Energy",sub_industry:"Energy"},
  OMC: {name:"Omnicom Group",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  OKE: {name:"ONEOK",sector:"Energy",sub_industry:"Energy"},
  ORCL: {name:"Oracle Corp.",sector:"Information Technology",sub_industry:"Information Technology"},
  OI: {name:"Owens-Illinois Inc",sector:"Materials",sub_industry:"Materials"},
  PCAR: {name:"PACCAR Inc.",sector:"Industrials",sub_industry:"Industrials"},
  PH: {name:"Parker-Hannifin",sector:"Industrials",sub_industry:"Industrials"},
  PDCO: {name:"Patterson Companies",sector:"Health Care",sub_industry:"Health Care"},
  PAYX: {name:"Paychex Inc.",sector:"Information Technology",sub_industry:"Information Technology"},
  PYPL: {name:"PayPal",sector:"Information Technology",sub_industry:"Information Technology"},
  PNR: {name:"Pentair Ltd.",sector:"Industrials",sub_industry:"Industrials"},
  PBCT: {name:"People's United Financial",sector:"Financials",sub_industry:"Financials"},
  POM: {name:"Pepco Holdings Inc.",sector:"Utilities",sub_industry:"Utilities"},
  PEP: {name:"PepsiCo Inc.",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  PKI: {name:"PerkinElmer",sector:"Health Care",sub_industry:"Health Care"},
  PRGO: {name:"Perrigo",sector:"Health Care",sub_industry:"Health Care"},
  PFE: {name:"Pfizer Inc.",sector:"Health Care",sub_industry:"Health Care"},
  PCG: {name:"PG&E Corp.",sector:"Utilities",sub_industry:"Utilities"},
  PM: {name:"Philip Morris International",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  PSX: {name:"Phillips 66",sector:"Energy",sub_industry:"Energy"},
  PNW: {name:"Pinnacle West Capital",sector:"Utilities",sub_industry:"Utilities"},
  PXD: {name:"Pioneer Natural Resources",sector:"Energy",sub_industry:"Energy"},
  PBI: {name:"Pitney-Bowes",sector:"Industrials",sub_industry:"Industrials"},
  PCL: {name:"Plum Creek Timber Co.",sector:"Financials",sub_industry:"Financials"},
  PNC: {name:"PNC Financial Services",sector:"Financials",sub_industry:"Financials"},
  RL: {name:"Polo Ralph Lauren Corp.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  PPG: {name:"PPG Industries",sector:"Materials",sub_industry:"Materials"},
  PPL: {name:"PPL Corp.",sector:"Utilities",sub_industry:"Utilities"},
  PX: {name:"Praxair Inc.",sector:"Materials",sub_industry:"Materials"},
  PCP: {name:"Precision Castparts",sector:"Industrials",sub_industry:"Industrials"},
  PCLN: {name:"Priceline.com Inc",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  PFG: {name:"Principal Financial Group",sector:"Financials",sub_industry:"Financials"},
  PG: {name:"Procter & Gamble",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  PGR: {name:"Progressive Corp.",sector:"Financials",sub_industry:"Financials"},
  PLD: {name:"Prologis",sector:"Financials",sub_industry:"Financials"},
  PRU: {name:"Prudential Financial",sector:"Financials",sub_industry:"Financials"},
  PEG: {name:"Public Serv. Enterprise Inc.",sector:"Utilities",sub_industry:"Utilities"},
  PSA: {name:"Public Storage",sector:"Financials",sub_industry:"Financials"},
  PHM: {name:"Pulte Homes Inc.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  PVH: {name:"PVH Corp.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  QRVO: {name:"Qorvo",sector:"Information Technology",sub_industry:"Information Technology"},
  PWR: {name:"Quanta Services Inc.",sector:"Industrials",sub_industry:"Industrials"},
  QCOM: {name:"QUALCOMM Inc.",sector:"Information Technology",sub_industry:"Information Technology"},
  DGX: {name:"Quest Diagnostics",sector:"Health Care",sub_industry:"Health Care"},
  RRC: {name:"Range Resources Corp.",sector:"Energy",sub_industry:"Energy"},
  RTN: {name:"Raytheon Co.",sector:"Industrials",sub_industry:"Industrials"},
  O: {name:"Realty Income Corporation",sector:"Financials",sub_industry:"Financials"},
  RHT: {name:"Red Hat Inc.",sector:"Information Technology",sub_industry:"Information Technology"},
  REGN: {name:"Regeneron",sector:"Health Care",sub_industry:"Health Care"},
  RF: {name:"Regions Financial Corp.",sector:"Financials",sub_industry:"Financials"},
  RSG: {name:"Republic Services Inc",sector:"Industrials",sub_industry:"Industrials"},
  RAI: {name:"Reynolds American Inc.",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  RHI: {name:"Robert Half International",sector:"Industrials",sub_industry:"Industrials"},
  ROK: {name:"Rockwell Automation Inc.",sector:"Industrials",sub_industry:"Industrials"},
  COL: {name:"Rockwell Collins",sector:"Industrials",sub_industry:"Industrials"},
  ROP: {name:"Roper Industries",sector:"Industrials",sub_industry:"Industrials"},
  ROST: {name:"Ross Stores",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  RCL: {name:"Royal Caribbean Cruises Ltd",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  R: {name:"Ryder System",sector:"Industrials",sub_industry:"Industrials"},
  CRM: {name:"Salesforce.com",sector:"Information Technology",sub_industry:"Information Technology"},
  SNDK: {name:"SanDisk Corporation",sector:"Information Technology",sub_industry:"Information Technology"},
  SCG: {name:"SCANA Corp",sector:"Utilities",sub_industry:"Utilities"},
  SLB: {name:"Schlumberger Ltd.",sector:"Energy",sub_industry:"Energy"},
  SNI: {name:"Scripps Networks Interactive Inc.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  STX: {name:"Seagate Technology",sector:"Information Technology",sub_industry:"Information Technology"},
  SEE: {name:"Sealed Air Corp.(New)",sector:"Materials",sub_industry:"Materials"},
  SRE: {name:"Sempra Energy",sector:"Utilities",sub_industry:"Utilities"},
  SHW: {name:"Sherwin-Williams",sector:"Materials",sub_industry:"Materials"},
  SIAL: {name:"Sigma-Aldrich",sector:"Materials",sub_industry:"Materials"},
  SIG: {name:"Signet Jewelers",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  SPG: {name:"Simon Property Group Inc",sector:"Financials",sub_industry:"Financials"},
  SWKS: {name:"Skyworks Solutions",sector:"Information Technology",sub_industry:"Information Technology"},
  SLG: {name:"SL Green Realty",sector:"Financials",sub_industry:"Financials"},
  SJM: {name:"Smucker (J.M.)",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  SNA: {name:"Snap-On Inc.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  SO: {name:"Southern Co.",sector:"Utilities",sub_industry:"Utilities"},
  LUV: {name:"Southwest Airlines",sector:"Industrials",sub_industry:"Industrials"},
  SWN: {name:"Southwestern Energy",sector:"Energy",sub_industry:"Energy"},
  SE: {name:"Spectra Energy Corp.",sector:"Energy",sub_industry:"Energy"},
  STJ: {name:"St Jude Medical",sector:"Health Care",sub_industry:"Health Care"},
  SWK: {name:"Stanley Black & Decker",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  SPLS: {name:"Staples Inc.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  SBUX: {name:"Starbucks Corp.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  HOT: {name:"Starwood Hotels & Resorts",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  STT: {name:"State Street Corp.",sector:"Financials",sub_industry:"Financials"},
  SRCL: {name:"Stericycle Inc",sector:"Industrials",sub_industry:"Industrials"},
  SYK: {name:"Stryker Corp.",sector:"Health Care",sub_industry:"Health Care"},
  STI: {name:"SunTrust Banks",sector:"Financials",sub_industry:"Financials"},
  SYMC: {name:"Symantec Corp.",sector:"Information Technology",sub_industry:"Information Technology"},
  SYY: {name:"Sysco Corp.",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  TROW: {name:"T. Rowe Price Group",sector:"Financials",sub_industry:"Financials"},
  TGT: {name:"Target Corp.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  TEL: {name:"TE Connectivity Ltd.",sector:"Information Technology",sub_industry:"Information Technology"},
  TE: {name:"TECO Energy",sector:"Utilities",sub_industry:"Utilities"},
  TGNA: {name:"Tegna",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  THC: {name:"Tenet Healthcare Corp.",sector:"Health Care",sub_industry:"Health Care"},
  TDC: {name:"Teradata Corp.",sector:"Information Technology",sub_industry:"Information Technology"},
  TSO: {name:"Tesoro Petroleum Co.",sector:"Energy",sub_industry:"Energy"},
  TXN: {name:"Texas Instruments",sector:"Information Technology",sub_industry:"Information Technology"},
  TXT: {name:"Textron Inc.",sector:"Industrials",sub_industry:"Industrials"},
  HSY: {name:"The Hershey Company",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  TRV: {name:"The Travelers Companies Inc.",sector:"Financials",sub_industry:"Financials"},
  TMO: {name:"Thermo Fisher Scientific",sector:"Health Care",sub_industry:"Health Care"},
  TIF: {name:"Tiffany & Co.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  TWX: {name:"Time Warner Inc.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  TWC: {name:"Time Warner Cable Inc.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  TJX: {name:"TJX Companies Inc.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  TMK: {name:"Torchmark Corp.",sector:"Financials",sub_industry:"Financials"},
  TSS: {name:"Total System Services",sector:"Information Technology",sub_industry:"Information Technology"},
  TSCO: {name:"Tractor Supply Company",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  RIG: {name:"Transocean",sector:"Energy",sub_industry:"Energy"},
  TRIP: {name:"TripAdvisor",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  FOXA: {name:"Twenty-First Century Fox Class A",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  FOX: {name:"Twenty-First Century Fox Class B",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  TSN: {name:"Tyson Foods",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  TYC: {name:"Tyco International",sector:"Industrials",sub_industry:"Industrials"},
  USB: {name:"U.S. Bancorp",sector:"Financials",sub_industry:"Financials"},
  UA: {name:"Under Armour",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  UNP: {name:"Union Pacific",sector:"Industrials",sub_industry:"Industrials"},
  UAL: {name:"United Continental Holdings",sector:"Industrials",sub_industry:"Industrials"},
  UNH: {name:"United Health Group Inc.",sector:"Health Care",sub_industry:"Health Care"},
  UPS: {name:"United Parcel Service",sector:"Industrials",sub_industry:"Industrials"},
  URI: {name:"United Rentals, Inc.",sector:"Industrials",sub_industry:"Industrials"},
  UTX: {name:"United Technologies",sector:"Industrials",sub_industry:"Industrials"},
  UHS: {name:"Universal Health Services, Inc.",sector:"Health Care",sub_industry:"Health Care"},
  UNM: {name:"Unum Group",sector:"Financials",sub_industry:"Financials"},
  URBN: {name:"Urban Outfitters",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  VFC: {name:"V.F. Corp.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  VLO: {name:"Valero Energy",sector:"Energy",sub_industry:"Energy"},
  VAR: {name:"Varian Medical Systems",sector:"Health Care",sub_industry:"Health Care"},
  VTR: {name:"Ventas Inc",sector:"Financials",sub_industry:"Financials"},
  VRSN: {name:"Verisign Inc.",sector:"Information Technology",sub_industry:"Information Technology"},
  VZ: {name:"Verizon Communications",sector:"Telecommunications Services",sub_industry:"Telecommunications Services"},
  VRTX: {name:"Vertex Pharmaceuticals Inc",sector:"Health Care",sub_industry:"Health Care"},
  VIAB: {name:"Viacom Inc.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  V: {name:"Visa Inc.",sector:"Information Technology",sub_industry:"Information Technology"},
  VNO: {name:"Vornado Realty Trust",sector:"Financials",sub_industry:"Financials"},
  VMC: {name:"Vulcan Materials",sector:"Materials",sub_industry:"Materials"},
  WMT: {name:"Wal-Mart Stores",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  WBA: {name:"Walgreens Boots Alliance",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  DIS: {name:"The Walt Disney Company",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  WM: {name:"Waste Management Inc.",sector:"Industrials",sub_industry:"Industrials"},
  WAT: {name:"Waters Corporation",sector:"Health Care",sub_industry:"Health Care"},
  ANTM: {name:"Anthem Inc.",sector:"Health Care",sub_industry:"Health Care"},
  WFC: {name:"Wells Fargo",sector:"Financials",sub_industry:"Financials"},
  WDC: {name:"Western Digital",sector:"Information Technology",sub_industry:"Information Technology"},
  WU: {name:"Western Union Co",sector:"Information Technology",sub_industry:"Information Technology"},
  WY: {name:"Weyerhaeuser Corp.",sector:"Financials",sub_industry:"Financials"},
  WHR: {name:"Whirlpool Corp.",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  WFM: {name:"Whole Foods Market",sector:"Consumer Staples",sub_industry:"Consumer Staples"},
  WMB: {name:"Williams Cos.",sector:"Energy",sub_industry:"Energy"},
  WEC: {name:"Wisconsin Energy Corporation",sector:"Utilities",sub_industry:"Utilities"},
  WYN: {name:"Wyndham Worldwide",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  WYNN: {name:"Wynn Resorts Ltd",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  XEL: {name:"Xcel Energy Inc",sector:"Utilities",sub_industry:"Utilities"},
  XRX: {name:"Xerox Corp.",sector:"Information Technology",sub_industry:"Information Technology"},
  XLNX: {name:"Xilinx Inc",sector:"Information Technology",sub_industry:"Information Technology"},
  XL: {name:"XL Capital",sector:"Financials",sub_industry:"Financials"},
  XYL: {name:"Xylem Inc.",sector:"Industrials",sub_industry:"Industrials"},
  YHOO: {name:"Yahoo Inc.",sector:"Information Technology",sub_industry:"Information Technology"},
  YUM: {name:"Yum! Brands Inc",sector:"Consumer Discretionary",sub_industry:"Consumer Discretionary"},
  ZBH: {name:"Zimmer Biomet Holdings",sector:"Health Care",sub_industry:"Health Care"},
  ZION: {name:"Zions Bancorp",sector:"Financials",sub_industry:"Financials"},
  ZTS: {name:"Zoetis",sector:"Health Care",sub_industry:"Health Care"},
)

quotes = TradierClient.instance.connection.quote(stocks.keys.map(&:to_s))
quotes.each do |quote|
  company = Company.new(
    symbol: quote.symbol,
    name: stocks[quote.symbol].name,
    sector: stocks[quote.symbol].sector,
    sub_industry: stocks[quote.symbol].sub_industry,
  )
  company.assign_tradier_quote(quote)
  company.save!
end
